# -*- coding: utf-8 -*-
"""251125_부동산agent_정책반영.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a2C8FqV_L9VoiUWa7164jA0AOQpXj6s0
"""

!pip install -q \
  "langchain==0.2.16" \
  "langchain-community==0.2.12" \
  "langchain-core==0.2.38" \
  "langsmith<0.2.0" \
  "sentence-transformers" \
  "elasticsearch" \
  "duckduckgo-search" \
  "pypdf"

import langchain
from sentence_transformers import SentenceTransformer
from elasticsearch import Elasticsearch
from duckduckgo_search import DDGS
from pypdf import PdfReader

print("모듈 임포트 성공!")

# Commented out IPython magic to ensure Python compatibility.
# %pip uninstall -y jax jaxlib

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q \
  "langchain==0.2.16" \
  "langchain-community==0.2.12" \
  "langchain-core==0.2.38" \
  "langsmith<0.2.0" \
  sentence-transformers \
  elasticsearch \
  duckduckgo-search \
  pypdf

# Commented out IPython magic to ensure Python compatibility.
# %pip uninstall -y sentence-transformers huggingface-hub

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q \
  "sentence-transformers==2.2.2" \
  "huggingface_hub==0.16.4"

import langchain
from sentence_transformers import SentenceTransformer
from elasticsearch import Elasticsearch
from duckduckgo_search import DDGS
from pypdf import PdfReader

print("✅ 라이브러리 임포트 성공!")

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q \
  "langchain==0.2.16" \
  "langchain-community==0.2.12" \
  "langchain-core==0.2.38" \
  "langsmith<0.2.0" \
  "huggingface_hub==0.14.1" \
  "sentence-transformers==2.2.2" \
  elasticsearch \
  duckduckgo-search \
  pypdf \
  torch

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q \
  "langchain==0.2.16" \
  "langchain-community==0.2.12" \
  "langchain-core==0.2.38" \
  "langchain-openai==0.1.23" \
  elasticsearch \
  duckduckgo-search \
  pypdf

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from elasticsearch import Elasticsearch
from duckduckgo_search import DDGS
from pypdf import PdfReader

print("✅ 임포트 성공!")

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q InstructorEmbedding

# === 공통 import ===
import os
from datetime import date, timedelta
from typing import List, Dict, Any, Tuple, Optional

from elasticsearch import Elasticsearch
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from duckduckgo_search import DDGS
from pypdf import PdfReader  # 나중에 정책 PDF 인덱싱 때 사용

# === OpenAI API Key (Colab에서 안전하게 입력) ===
import getpass

if "OPENAI_API_KEY" not in os.environ:
    os.environ["OPENAI_API_KEY"] = getpass.getpass("🔑 OpenAI API Key 입력: ")

# === ElasticSearch 환경설정 ===
ES_HOST = os.getenv("ES_HOST", "https://my-elasticsearch-project-b71e61.es.us-central1.gcp.elastic.cloud:443")          # 네 ES 주소
ES_REAL_INDEX = os.getenv("ES_REAL_INDEX", "realestate_hybrid")  # 실거래/매물 인덱스
ES_POLICY_INDEX = os.getenv("ES_POLICY_INDEX", "gov_policy_korea")  # 정책 PDF 인덱스

# === ES 클라이언트 생성 ===
es = Elasticsearch(ES_HOST)

def check_es():
    if not es.ping():
        raise RuntimeError(f"Elasticsearch({ES_HOST}) 가 응답하지 않습니다. Docker/Cloud 상태를 확인하세요.")

# === LLM & Embedding 설정 ===
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.2)

# text-embedding-3-small: 1536차원, 가격 저렴, 한글도 괜찮음
embedding_model = OpenAIEmbeddings(model="text-embedding-3-small")

def embed_query(text: str) -> List[float]:
    """
    OpenAI 임베딩을 사용해 쿼리를 벡터(list[float])로 변환.
    ES knn 쿼리에 그대로 넣어 쓸 수 있다.
    """
    return embedding_model.embed_query(text)

import os, getpass
from elasticsearch import Elasticsearch

# 1) Elastic Cloud endpoint (복붙)
ES_HOST = "https://my-elasticsearch-project-b71e61.es.us-central1.gcp.elastic.cloud:443"

# 2) API Key는 getpass로 입력해서 노트북에 안 남게
if "ES_API_KEY" not in os.environ:
    os.environ["ES_API_KEY"] = getpass.getpass("🔑 Elastic API Key 입력: ")

ES_API_KEY = os.environ["ES_API_KEY"]

# 3) ES 클라이언트 생성 (API key 인증)
es = Elasticsearch(
    ES_HOST,
    api_key=ES_API_KEY,
    verify_certs=True,
    request_timeout=30,
)

def check_es():
    try:
        info = es.info()
        print("[ES 연결 성공]", info["cluster_name"], info["version"]["number"])
        return True
    except Exception as e:
        raise RuntimeError(f"Elasticsearch({ES_HOST}) 연결 실패: {e}")

from langchain.text_splitter import RecursiveCharacterTextSplitter

# Colab에 업로드한 정책 PDF 경로
POLICY_PDFS = [
    "/content/R25_0627.pdf",
    "/content/R25_0907.pdf",
    "/content/R25_1015.pdf",
]

def parse_date_from_filename(filename: str) -> str:
    """
    파일명 예: R25_0627.pdf → 2025-06-27 로 변환 (연도는 2025로 가정)
    """
    base = os.path.basename(filename)
    mmdd = base.split("_")[1].split(".")[0]  # "0627"
    mm = mmdd[:2]
    dd = mmdd[2:]
    return f"2025-{mm}-{dd}"


def create_policy_index_if_needed():
    """
    정책 인덱스가 없으면 text-embedding-3-small 차원(1536)으로 생성.
    """
    check_es()
    if es.indices.exists(index=ES_POLICY_INDEX):
        print(f"[INFO] index '{ES_POLICY_INDEX}' already exists. skip create.")
        return

    dims = 1536  # text-embedding-3-small
    mapping = {
        "mappings": {
            "properties": {
                "content": {"type": "text"},
                "embedding": {
                    "type": "dense_vector",
                    "dims": dims,
                    "index": True,
                    "similarity": "cosine",
                },
                "policy_name": {"type": "keyword"},
                "published_date": {"type": "date", "format": "yyyy-MM-dd||strict_date_optional_time"},
                "source_file": {"type": "keyword"},
            }
        }
    }
    es.indices.create(index=ES_POLICY_INDEX, body=mapping)
    print(f"[INFO] created index '{ES_POLICY_INDEX}' (dims={dims})")


def index_policy_pdfs(pdf_paths: List[str]):
    """
    최근 3개 정책 PDF를:
      1) 페이지 단위로 로드
      2) 텍스트 청크로 분할
      3) OpenAI 임베딩 계산
      4) ES_POLICY_INDEX 에 인덱싱
    """
    create_policy_index_if_needed()

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=150,
        separators=["\n\n", "\n", " ", ""],
    )

    from tqdm import tqdm

    for path in pdf_paths:
        print(f"[INFO] indexing policy pdf: {path}")
        reader = PdfReader(path)
        pages = [page.extract_text() or "" for page in reader.pages]

        docs = []
        for i, text in enumerate(pages):
            docs.append(
                {
                    "page_content": text,
                    "metadata": {
                        "source_file": path,
                        "page": i,
                    },
                }
            )

        # 2) 청크 분할
        texts = [d["page_content"] for d in docs]
        # 간단하게 splitter를 직접 적용
        chunks = splitter.create_documents(texts)

        pub_date = parse_date_from_filename(path)

        # 3) OpenAI 임베딩 계산 (청크 단위)
        contents = [c.page_content for c in chunks]
        vectors = embedding_model.embed_documents(contents)

        # 4) ES 인덱싱
        for content, vec in tqdm(zip(contents, vectors), total=len(contents)):
            body = {
                "content": content,
                "embedding": vec,
                "policy_name": os.path.basename(path),
                "published_date": pub_date,
                "source_file": path,
            }
            es.index(index=ES_POLICY_INDEX, document=body)

    print("[INFO] policy pdf indexing done.")

index_policy_pdfs(POLICY_PDFS)

# ===== 4. 하이브리드 검색 + 평균가 + 상환 계산 =====
from typing import List, Dict, Any, Tuple, Optional
from datetime import date, timedelta

ES_REAL_INDEX = os.getenv("ES_REAL_INDEX", "realestate_hybrid")  # 네 실거래 인덱스 이름

def rrf_combine(sparse_hits, dense_hits, k: int = 60, top_k: int = 10):
    """
    Reciprocal Rank Fusion (RRF) 로 sparse/dense 결과 합치기
    """
    scores = {}
    for rank, h in enumerate(sparse_hits, start=1):
        _id = h["_id"]
        scores.setdefault(_id, 0.0)
        scores[_id] += 1.0 / (k + rank)

    for rank, h in enumerate(dense_hits, start=1):
        _id = h["_id"]
        scores.setdefault(_id, 0.0)
        scores[_id] += 1.0 / (k + rank)

    id_to_doc = {h["_id"]: h for h in sparse_hits}
    id_to_doc.update({h["_id"]: h for h in dense_hits})

    ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)[:top_k]
    return [id_to_doc[_id] for _id, _ in ranked]


def hybrid_search_apt(
    query: str = "",
    gu: str = "",
    dong: str = "",
    min_price_krw: int = 0,
    max_price_krw: int = 0,
    area_center: float = 0.0,
    area_tol: float = 3.0,
    min_year_built: int = 0,
    max_year_built: int = 0,
    recent_months: int = 0,
    size: int = 10,
) -> List[Dict[str, Any]]:
    """
    실거래 인덱스(ES_REAL_INDEX)를 대상으로 하는 하이브리드 검색.
    - 원래는 sparse + dense(RRF)인데,
    - dense(dim mismatch 등) 실패 시에는 자동으로 sparse-only 로 fallback.
    """
    check_es()

    filters = []
    if gu:
        filters.append({"term": {"gu": gu}})
    if dong:
        filters.append({"term": {"dong": dong}})

    if min_price_krw or max_price_krw:
        price_range = {}
        if min_price_krw:
            price_range["gte"] = min_price_krw
        if max_price_krw:
            price_range["lte"] = max_price_krw
        filters.append({"range": {"price_krw": price_range}})

    if area_center:
        filters.append(
            {
                "range": {
                    "area_m2": {
                        "gte": area_center - area_tol,
                        "lte": area_center + area_tol,
                    }
                }
            }
        )

    if min_year_built or max_year_built:
        year_range = {}
        if min_year_built:
            year_range["gte"] = min_year_built
        if max_year_built:
            year_range["lte"] = max_year_built
        filters.append({"range": {"year_built": year_range}})

    if recent_months:
        end = date.today()
        start = end - timedelta(days=30 * recent_months)
        filters.append(
            {
                "range": {
                    "deal_date": {
                        "gte": start.isoformat(),
                        "lte": end.isoformat(),
                    }
                }
            }
        )

# ---------- 1) Dense 검색 (실패 시 무시) ----------
    dense_hits = []
    query_text = query or f"{gu} {dong}"
    try:
        vec = embed_query(query_text)
        dense_res = es.search(
            index=ES_REAL_INDEX,
            knn={
                "field": "embedding",          # 인덱스의 dense_vector 필드명
                "query_vector": vec,
                "k": size * 2,
                "num_candidates": size * 4,
            },
            _source=True,
        )
        dense_hits = dense_res["hits"]["hits"]
    except Exception as e:
        # 여기서 방금 본 dimension mismatch 에러를 잡음
        print("[WARN] Dense 검색 실패, sparse-only 모드로 동작합니다:", repr(e))
        dense_hits = []

    # ---------- 2) Sparse 검색 ----------
    bool_q = {"must": [], "filter": filters}
    if query:
        bool_q["must"].append(
            {
                "multi_match": {
                    "query": query,
                    "fields": [
                        "apt_name^3",
                        "gu^2",
                        "dong^2",
                        "road_address",
                        "description",
                    ],
                }
            }
        )

    sparse_res = es.search(
        index=ES_REAL_INDEX,
        size=size * 2,
        query={"bool": bool_q},
        _source=True,
    )
    sparse_hits = sparse_res["hits"]["hits"]

     # ---------- 3) RRF 결합 (dense 없으면 사실상 sparse 정렬) ----------
    fused_hits = rrf_combine(sparse_hits, dense_hits, top_k=size)

    rows = []
    for h in fused_hits:
        src = h["_source"]
        rows.append(
            {
                "gu": src.get("gu"),
                "dong": src.get("dong"),
                "apt_name": src.get("apt_name"),
                "deal_date": src.get("deal_date"),
                "area_m2": src.get("area_m2"),
                "year_built": src.get("year_built"),
                "price_krw": src.get("price_krw"),
            }
        )
    return rows


def avg_price_last_3m(gu: str, area_center: float, tol: float = 1.5) -> Tuple[Optional[float], int]:
    """
    최근 3개월간 '구 + 면적대' 평균 실거래가.
    """
    check_es()
    today = date.today()
    start = (today - timedelta(days=90)).isoformat()
    end = today.isoformat()

    body = {
        "size": 0,
        "query": {
            "bool": {
                "must": [
                    {"term": {"gu": gu}},
                    {"range": {"deal_date": {"gte": start, "lte": end}}},
                    {
                        "range": {
                            "area_m2": {
                                "gte": area_center - tol,
                                "lte": area_center + tol,
                            }
                        }
                    },
                ]
            }
        },
        "aggs": {"avg_price": {"avg": {"field": "price_krw"}}},
    }
    res = es.search(index=ES_REAL_INDEX, body=body)
    avg = res["aggregations"]["avg_price"]["value"]
    count = res["hits"]["total"]["value"]
    if avg is None:
        return None, int(count)
    return float(avg), int(count)


def avg_price_last_3m_dong(gu: str, dong: str, area_center: float, tol: float = 1.5) -> Tuple[Optional[float], int]:
    """
    최근 3개월간 '구+동 + 면적대' 평균 실거래가.
    """
    check_es()
    today = date.today()
    start = (today - timedelta(days=90)).isoformat()
    end = today.isoformat()

    body = {
        "size": 0,
        "query": {
            "bool": {
                "must": [
                    {"term": {"gu": gu}},
                    {"term": {"dong": dong}},
                    {"range": {"deal_date": {"gte": start, "lte": end}}},
                    {
                        "range": {
                            "area_m2": {
                                "gte": area_center - tol,
                                "lte": area_center + tol,
                            }
                        }
                    },
                ]
            }
        },
        "aggs": {"avg_price": {"avg": {"field": "price_krw"}}},
    }
    res = es.search(index=ES_REAL_INDEX, body=body)
    avg = res["aggregations"]["avg_price"]["value"]
    count = res["hits"]["total"]["value"]
    if avg is None:
        return None, int(count)
    return float(avg), int(count)


def loan_payment(principal: int, annual_rate_pct: float, years: int) -> Dict[str, int]:
    """
    원리금균등 상환 계산.
    """
    months = years * 12
    if principal <= 0 or months <= 0:
        return {
            "monthly_payment": 0,
            "months": 0,
            "total_payment": 0,
            "total_interest": 0,
        }

    r = (annual_rate_pct / 100.0) / 12.0
    if r == 0:
        monthly = principal / months
    else:
        monthly = principal * (r * (1 + r) ** months) / ((1 + r) ** months - 1)

    total_payment = monthly * months
    total_interest = total_payment - principal
    return {
        "monthly_payment": int(monthly),
        "months": int(months),
        "total_payment": int(total_payment),
        "total_interest": int(total_interest),
    }

# ===== 5. LangChain Tools 정의 =====
from langchain.tools import tool
from langchain_community.tools.ddg_search import DuckDuckGoSearchRun

ddg_search = DuckDuckGoSearchRun(region="kr-kr", max_results=5)

# 평균가 숫자를 사람이 읽기 좋은 형식으로 바꿔주는 헬퍼
def _format_price_krw(amount: float) -> str:
    """원 단위 금액을 '1,654,095,055원 (약 16억 5천만 원)' 형식으로 변환"""
    amount = int(amount)
    eok = amount // 100_000_000          # 억
    man = (amount % 100_000_000) // 10_000  # 만
    man_rounded = (man // 1000) * 1000   # 1천만 단위로 반올림

    if eok > 0:
        return f"{amount:,}원 (약 {eok}억 {man_rounded}만 원)"
    else:
        return f"{amount:,}원"

@tool
def search_properties(
    query: str = "",
    gu: str = "",
    dong: str = "",
    max_price_krw: int = 0,
    min_price_krw: int = 0,
    area_center: float = 0.0,
    area_tol: float = 3.0,
    max_age_years: int = 0,
    recent_months: int = 0,
    top_k: int = 10,
) -> str:
    """
    부동산 매물 검색 도구 (ES 하이브리드).

    - query: 자유로운 텍스트 ("마포 59형 신축 10억 이하" 등)
    - gu, dong: 시군구 / 동 필터
    - max_price_krw, min_price_krw: 가격 범위 (원 단위)
    - area_center, area_tol: 전용면적 중심값 & 허용 오차 (예: 59㎡ ± 3㎡)
    - max_age_years: '최근 N년 이내 신축' 조건일 때 사용
    - recent_months: '최근 N개월 거래'만 보고 싶을 때
    - top_k: 반환할 매물 개수
    """
    min_year_built = 0
    if max_age_years:
        this_year = date.today().year
        min_year_built = this_year - max_age_years

    rows = hybrid_search_apt(
        query=query,
        gu=gu,
        dong=dong,
        min_price_krw=min_price_krw,
        max_price_krw=max_price_krw,
        area_center=area_center,
        area_tol=area_tol,
        min_year_built=min_year_built,
        size=top_k,
        recent_months=recent_months,
    )

    if not rows:
        return "검색 결과가 없습니다."

    lines = ["[PROPERTY_SEARCH_RESULT]"]
    for i, r in enumerate(rows, start=1):
        lines.append(
            f"{i}. {r['apt_name']} / {r['gu']} {r['dong']} / "
            f"{r['area_m2']}㎡ / {r['price_krw']:,}원 / {r['deal_date']} / "
            f"준공연도: {r['year_built']}"
        )
    return "\n".join(lines)


@tool(return_direct=True)
def avg_price_gu(gu: str, area_center: float) -> str:
    """
    구 + 면적대 기준 최근 3개월 평균 매매가를 한 문장으로 반환.
    """
    avg, cnt = avg_price_last_3m(gu=gu, area_center=area_center)
    if avg is None or cnt == 0:
        return f"현재 {gu} {area_center:.1f}㎡ 근처에는 최근 3개월 거래 내역이 없습니다."

    price_text = _format_price_krw(avg)
    return (
        f"{gu} {area_center:.1f}㎡대 아파트의 최근 3개월 평균 실거래가는 "
        f"{price_text} 기준입니다. (표본 {cnt}건)"
    )

@tool(return_direct=True)
def avg_price_dong(gu: str, dong: str, area_center: float) -> str:
    """
    구+동 + 면적대 기준 최근 3개월 평균 매매가를 한 문장으로 반환.
    """
    avg, cnt = avg_price_last_3m_dong(gu=gu, dong=dong, area_center=area_center)
    if avg is None or cnt == 0:
        return f"현재 {gu} {dong} {area_center:.1f}㎡ 근처에는 최근 3개월 거래 내역이 없습니다."

    price_text = _format_price_krw(avg)
    return (
        f"{gu} {dong} {area_center:.1f}㎡대 아파트의 최근 3개월 평균 실거래가는 "
        f"{price_text} 기준입니다. (표본 {cnt}건)"
    )



@tool
def loan_policy_limit(query: str) -> str:
    """
    주택담보대출 한도를 추정하는 정책 RAG 도구 (심플+우대조건 반영 버전).

    query 안에는 다음 정보를 자연어로 최대한 포함해서 넣는다.
    - 주택가격(예: 16억, 8억5천 등)
    - 보유 현금(있다면)
    - 지역(구 단위) / 규제지역 여부(투기과열지구, 조정대상지역, 비규제 등)
    - 가구 유형: 무주택, 1주택 갈아타기, 다주택, 생애최초, 신혼부부 등
    - 한도만 간단히 알고 싶다는 의도

    예시:
    "2025년 기준 서울 마포구(투기과열지구) 16억짜리 84제곱 아파트를
     생애최초로 구입하려는 무주택 신혼부부이고, 보유 현금은 5억이다.
     정책상 받을 수 있는 주택담보대출 한도를 대략 알고 싶다."
    """

    check_es()

    # 1) 정책 PDF에서 관련 문단 검색
    vec = embed_query(query)
    res = es.search(
        index=ES_POLICY_INDEX,
        knn={
            "field": "embedding",
            "query_vector": vec,
            "k": 6,
            "num_candidates": 12,
        },
        _source=True,
    )
    chunks = [h["_source"]["content"] for h in res["hits"]["hits"]]
    if not chunks:
        return "[LOAN_POLICY_LIMIT]\n관련 정책 문서를 찾지 못했습니다."

    context = "\n\n---\n\n".join(chunks)

    # 2) LLM에게 요약 지시
    prompt = f"""
너는 한국 주택담보대출 상담사다.

[사용자 질문]
{query}

[정책 문서 발췌]
{context}

역할:
1) 위 정책 문서에서 LTV/DTI/DSR 관련 규정을 읽고,
   아래 조건에 따라 적용될 수 있는 LTV 비율을 "대략 한 값"으로 하나 정해라.
   - query 안에 '신혼부부', '생애최초', '무주택' 등이 있으면,
     해당 우대 규정(생애최초/신혼부부 특례 등)을 우선 고려한다.
   - '1주택', '갈아타기'가 언급되면, 기존 주택 보유에 따른 규제(LTV 축소, 처분 조건 등)를 고려한다.
   - 별도 표현이 없으면 일반 무주택 가구로 가정한다.
2) 사용자가 말한 주택가격을 기준으로 이론상 최대 대출 가능 금액을 계산하되,
   계산 과정은 네 머릿속에서 하고, 최종 결과만 말해라.
3) 한국 실무 관행상 일반적인 최대 한도를 6억원 수준으로 본다고 가정하고,
   계산상 금액이 6억원을 초과하면
   "계산상은 X억이지만 정책상 일반 한도는 6억 원이라 실제로는 6억 원 수준"이라고 설명하라.
4) DTI/DSR은 숫자를 자세히 말할 필요는 없고,
   - 무주택/신혼부부의 경우 "DTI/DSR 범위 내에서 6억 원 수준을 기대할 수 있다" 정도로,
   - 1주택/다주택의 경우 "DTI/DSR 및 보유 주택수에 따라 실제 한도는 더 줄어들 수 있다" 정도로
   한 문장만 언급하라.

출력 형식 (반드시 한 줄, 문장 하나만):
- 주택가격, 적용 LTV(대략 값), 대략적인 최대 대출 가능 금액(억 단위 반올림),
  신혼부부/생애최초/1주택 여부에 따른 코멘트, 6억원 상한 여부를 모두 포함해
  자연스럽게 한 문장으로 설명할 것.
- 예시:
  "무주택 신혼부부가 16억 원 아파트를 구입할 경우 생애최초 우대를 반영해 LTV 약 40%를 적용하면
   계산상 최대 대출은 약 6억 4천만 원이지만, 정책상 일반 한도가 6억 원이라 실제 받을 수 있는 한도는
   약 6억 원 수준이며 DSR 규제에 따라 다소 조정될 수 있습니다."

그 외 불필요한 설명이나 여러 문장은 쓰지 말고,
위 예시처럼 한 줄짜리 한국어 문장만 출력하라.
"""

    answer = llm.invoke(prompt)
    return "[LOAN_POLICY_LIMIT]\n" + answer.content



@tool
def loan_simulation(total_price_krw: int, cash_krw: int, annual_rate_pct: float = 3.8, years: int = 30) -> str:
    """
    매매가/자기자본/금리/기간을 입력하면 대출 원리금 상환 스케줄 요약.
    """
    principal = total_price_krw - cash_krw
    if principal <= 0:
        return (
            "[LOAN_SIMULATION]\n"
            f"매매가 {total_price_krw:,}원, 현금 {cash_krw:,}원 기준으로 대출이 필요하지 않습니다."
        )
    res = loan_payment(principal, annual_rate_pct, years)
    return (
        "[LOAN_SIMULATION]\n"
        f"대출 원금: {principal:,}원\n"
        f"연 이자율: {annual_rate_pct:.2f}% / 기간: {years}년({res['months']}개월)\n"
        f"월 상환액: {res['monthly_payment']:,}원\n"
        f"총 상환액: {res['total_payment']:,}원 (이자 {res['total_interest']:,}원)"
    )


@tool
def policy_news_search(query: str) -> str:
    """
    DuckDuckGo Web Search 기반 정책 뉴스/동향 검색 (외부 도구 요건).
    """
    result = ddg_search.run(query + " 주택담보대출 정책 변화 site:gov.kr OR site:bizinfo.go.kr")
    return f"[POLICY_NEWS]\n{result}"

# ===== 6. Agent 구성 =====
from langchain.agents import initialize_agent, AgentType
from langchain.memory import ConversationBufferMemory

def get_llm():
    # 필요하면 temperature 조절해서 버전 바꿔도 됨
    return llm  # 위에서 만든 ChatOpenAI 인스턴스 재사용

tools = [
    search_properties,
    avg_price_gu,
    avg_price_dong,
    loan_policy_limit,
    loan_simulation,
    policy_news_search,
]

memory = ConversationBufferMemory(
    memory_key="chat_history",
    return_messages=True,
)

SYSTEM_PROMPT = """
너는 한국 부동산 상담 AI 에이전트야.

대화 흐름은 기본적으로 다음과 같이 진행하라:
1) 사용자의 예산/면적/지역 조건을 파악한 뒤, search_properties 도구로 후보 아파트를 찾는다.
2) 같은 면적대의 최근 3개월 평균가격을 avg_price_gu 또는 avg_price_dong 도구로 조회하여,
   '후보 매물이 평균 대비 비싼지/싼지'를 함께 설명한다.
3) 사용자가 대출/한도를 물어보면 loan_policy_limit 도구를 사용해
   최근 3개 정책 PDF (gov_policy_korea 인덱스)를 기반으로 대략적인 한도를 추정한다.
4) 이후 loan_simulation 도구를 사용해 월 상환액/총 상환액을 계산한다.
5) 정책 리스크나 향후 변화 가능성을 설명할 때만 policy_news_search 도구를 사용해
   최신 정책/뉴스 동향을 덧붙여라.
6) 여러 턴에 걸쳐 사용자의 조건(연소득, 무주택 여부, 희망 지역, 예산)을 기억하고 활용하라.

추가 규칙:
- 도구(특히 [AVG_PRICE_GU], [AVG_PRICE_DONG], [LOAN_POLICY_LIMIT])에서 제공한 숫자 값(가격, 월 상환액 등)은
  그대로 신뢰해야 한다. Final Answer에서 이 숫자를 다시 계산하거나 자릿수를 바꾸지 말 것.
- '최근 3개월 평균 실거래가: 1,654,095,055원'처럼 나오면,
  답변에서는 '최근 3개월 평균 거래가는 1,654,095,055원(약 16억 5천만 원)입니다.'처럼
  **도구가 준 숫자를 그대로 쓰고, 필요하면 옆에 억 단위 설명만 덧붙여라.**
- 1,654,095,055원 같은 값을 1억대로 잘못 줄여 쓰지 말고,
  최소한 앞의 두 자리(16억) 수준은 정확히 유지해야 한다
"""

agent_llm = get_llm()

agent = initialize_agent(
    tools=tools,
    llm=agent_llm,
    agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,  # ✅ 여기 변경
    memory=memory,
    verbose=False,
    agent_kwargs={"system_message": SYSTEM_PROMPT},
)

def chat_realestate_agent(user_input: str) -> str:
    return agent.run(user_input)

chat_realestate_agent("마포구 59㎡, 예산 10억 정도로 집 추천해줘.")

resp1 = chat_realestate_agent("마포구 59제곱, 예산 10억 정도로 집 추천해줘.")
resp2 = chat_realestate_agent("그럼 마포구 84제곱은 최근 3개월 평균 거래가 얼마야?")
print(resp1)
print("------")
print(resp2)

resp3 = chat_realestate_agent(
    "방금 말한 마포구 84제곱 아파트 평균 매매가를 16억 5천만 원 정도라고 가정하면, "
    "나는 무주택 신혼부부고 보유 현금은 5억 원이야. "
    "현재 주택담보대출 정책 기준으로 받을 수 있는 대출 한도가 "
    "LTV 기준으로 어느 정도인지 한 줄로만 설명해줘."
)
print(resp3)

resp4 = chat_realestate_agent(
    "아까 정책 기준으로 최대 대출 가능 금액이 약 6억 원 정도라고 했잖아. "
    "그중 4억 원을 연 3.8% 금리, 30년 원리금균등 상환으로 대출받는다고 하면 "
    "월 상환액과 총 상환액, 총 이자 부담을 계산해서 알려줘."
)
print(resp4)

