# -*- coding: utf-8 -*-
"""국토교통부 실거래가 오픈API - 251118

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Z6KTiW3EVzZYqV8KQ0DKnDAqBPmo9F6

# 국토교통부 실거래가 오픈API - 데이터 수집

## 공공데이터 포털

[https://www.data.go.kr](https://www.data.go.kr/)

## 법정동 코드 가져오기
"""

import pandas as pd

url = 'https://docs.google.com/uc?export=download&id=1lW2-FvsmdYRiY90379lyj7yTIWA5LR6Q'
df_code = pd.read_excel(url, dtype=str)
df_code = df_code.query("폐지여부 == '존재'")
df_code

df_gu = df_code.query('법정동코드.str.contains("11[^0][0-9]{2}00000")')
df_gu

len(df_gu)

"""## 국토교통부 아파트매매 실거래자료
국토교통부 RTMS (Realestate Trade Management System)
"""

# pip install pyOpenSSL

# 국토교통부 실거래가
import requests
from bs4 import BeautifulSoup


service_key = ''    #내꺼야  일반 인증키 decoding

url = 'http://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade'
params ={
    'LAWD_CD' : '11110',        # 지역 코드 법정동코드 10자리 중 앞 5자리
    'DEAL_YMD' : '202510',      # 계약년월(YYYYMM 6자리)
    'serviceKey': service_key,  # API키
}

r = requests.get(url, params=params)
r.text

"""url = "http://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade?LAWD_CD=11110&DEAL_YMD=202508&serviceKey=fmsXpA/eJwM0lFW4U61wxlvPmf/18zX991bEl1NNULASWVlB0jtFTuvi2Xg5EKSyYgCKn0lp6azA9bmC4eFNsA=="
"""

print(r.request.url)

import pandas as pd
import io

df = pd.read_xml(io.StringIO(r.text), xpath='//item')
df

"""## 데이터 전처리"""

df.dtypes # 컬럼별 데이터 타입 확인

"""### 1. '거래금액' 문자열을 수치값으로 변환하기"""

df['dealAmount'] = df['dealAmount'].str.replace(',', '').astype(int)

"""### 2. '년', '월', '일' - 합쳐서 날짜(거래일)로 변환하기"""

df['dealYear'].astype(str) + \
df['dealMonth'].astype(str).str.zfill(2) + \
df['dealDay'].astype(str).str.zfill(2)

# 거래일(dealDate)
df['dealDate'] = df['dealYear'].astype(str) + \
                 df['dealMonth'].astype(str).str.zfill(2) + \
                 df['dealDay'].astype(str).str.zfill(2)

df['dealDate'] = pd.to_datetime(df['dealDate'])

"""## 3. 시군구 코드(sggCd)"""

df['sggCd'] = df['sggCd'].astype(str)

"""## 타입 확인"""

df.info()

"""## 페이징"""

# 국토교통부 실거래가
import requests
from bs4 import BeautifulSoup

## api 내꺼로 바꿀것
service_key = 'fmsXpA/eJwM0lFW4U61wxlvPmf/18zX991bEl1NNULASWVlB0jtFTuvi2Xg5EKSyYgCKn0lp6azA9bmC4eFNsA=='

url = 'http://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade'
params ={
    'LAWD_CD' : '11110',        # 지역 코드 법정동코드 10자리 중 앞 5자리
    'DEAL_YMD' : '202510',      # 계약년월(YYYYMM 6자리)
    'serviceKey': service_key,  # API키
    'numOfRows': 10000,         # 1달에 최대 1만건
}

r = requests.get(url, params=params)
r.text

from bs4 import BeautifulSoup

soup = BeautifulSoup(r.text, 'xml')
total_count = soup.find('totalCount').text
num_of_rows = soup.find('numOfRows').text
page_no = soup.find('pageNo').text

print(f"Total Count: {total_count}")
print(f"Number of Rows: {num_of_rows}")
print(f"Page No: {page_no}")

"""## 일정기간 데이터 수집하기 (3개년)"""

# 날짜 생성
dates = pd.date_range('2023-01-01', '2025-10-31', freq='MS')
dates

lawd_code = '1168000000'[:5] # 서울특별시 강남구
service_key = 'fmsXpA/eJwM0lFW4U61wxlvPmf/18zX991bEl1NNULASWVlB0jtFTuvi2Xg5EKSyYgCKn0lp6azA9bmC4eFNsA=='

dfs = []
for date in dates:
    params = {
         'LAWD_CD' : lawd_code,      # 지역 코드 법정동코드 10자리 중 앞 5자리
         'DEAL_YMD' : date.strftime("%Y%m"),      # 계약년월(YYYYMM 6자리)
         'serviceKey': service_key,  # API키
         'numOfRows': 10000,         # 1달에 최대 1만건
    }
    url = 'http://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade'
    r = requests.get(url, params=params)
    df_tmp = pd.read_xml(io.StringIO(r.text), xpath='//item')
    dfs.append(df_tmp)

merged = pd.concat(dfs)
merged

merged.reset_index(drop=True,  inplace=True)
merged

"""## 정리 (함수로 만들기)

"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

service_key = 'fmsXpA/eJwM0lFW4U61wxlvPmf/18zX991bEl1NNULASWVlB0jtFTuvi2Xg5EKSyYgCKn0lp6azA9bmC4eFNsA==' # Updated service_key

def 국토교통부_실거래가(lawd_code, start, end):
    lawd_code = lawd_code[:5] if len(lawd_code) == 10 else lawd_code

    dfs = []
    for date in pd.date_range(start, end, freq='MS'):
        params = {
            'LAWD_CD' : lawd_code,               # 지역 코드 법정동코드 10자리 중 앞 5자리
            'DEAL_YMD' : date.strftime('%Y%m'),  # 계약년월(YYYYMM 6자리)
            'serviceKey': service_key,           # API키
            'numOfRows': 10000,
        }
        url = 'http://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade'
        r = requests.get(url, params=params)
        df_tmp = pd.read_xml(io.StringIO(r.text), xpath='//item')
        dfs.append(df_tmp)

    # 합치기
    df = pd.concat(dfs)

    # 거래금액(dealAmount)
    df['dealAmount'] = df['dealAmount'].str.replace(',', '').astype(int)

    # 거래일(dealDate)
    df['dealDate'] = df['dealYear'].astype(str) + \
                    df['dealMonth'].astype(str).str.zfill(2) + \
                    df['dealDay'].astype(str).str.zfill(2)
    df['dealDate'] = pd.to_datetime(df['dealDate'])
    # 시군구코드(sggCd)
    df['sggCd'] = df['sggCd'].astype(str)
    df = df.rename(columns={
        'aptDong': '아파트동',
        'aptNm': '아파트',
        'buildYear': '건축년도',
        'buyerGbn': '매수자구분',
        'cdealDay': '계약일자',
        'cdealType': '거래유형',
        'dealAmount': '거래금액',
        'dealDay': '일',
        'dealMonth': '월',
        'dealYear': '년',
        'dealingGbn': '거래구분',
        'estateAgentSggNm': '중개사소재지',
        'excluUseAr': '전용면적',
        'floor': '층',
        'jibun': '지번',
        'landLeaseholdGbn': '토지건물구분',
        'rgstDate': '등기일자',
        'sggCd': '시군구코드',
        'slerGbn': '매도자구분',
        'umdNm': '법정동',
        'dealDate': '거래일자'
    })
    return df

서울특별시_노원구 = 국토교통부_실거래가('1135000000', '2023-01-01', '2025-10-31')
서울특별시_노원구

서울특별시_송파구 = 국토교통부_실거래가('1171000000', '2023-01-01', '2025-10-31')
서울특별시_송파구

서울특별시_마포구 = 국토교통부_실거래가('1144000000', '2023-01-01', '2025-10-31')
서울특별시_마포구

result = pd.concat([서울특별시_마포구, 서울특별시_송파구, 서울특별시_노원구], axis=0, ignore_index=True)

df_gu

# 시군구코드(앞 5자리) + 구 이름 만들기
df_gu['시군구코드'] = df_gu['법정동코드'].str[:5]
df_gu['구명'] = df_gu['법정동명'].str.replace('서울특별시 ', '', regex=False)

# 매핑에 쓸 컬럼만 남기기
df_gu_3 = df_gu[['시군구코드', '구명']].drop_duplicates()

# 엑셀 파일로 저장하기

서울특별시_마포구.to_excel('서울특별시_마포구.xlsx', index=False)
서울특별시_노원구.to_excel('서울특별시_노원구.xlsx', index=False)
서울특별시_송파구.to_excel('서울특별시_송파구.xlsx', index=False)

result.to_excel('서울특별시_3개구_실거래가.xlsx', index=False)